
language: ruby
rvm:
  - 2.3.1
addons:
  code_climate:
    repo_token: 8782a3603d1dbaef9d4f18519b7389ce6fe16c7c9cab3c1603720fd9b0a6a4b2
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec cucumber
after_script:
  - bundle exec rake send_to_codeclimate 
